# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python 3.11 image from the Python foundation.
FROM python:3.11-slim AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file into the image
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application directory
COPY . .

# Set environment variables
ENV MSSQL_DRIVER=mssql_driver
ENV MSSQL_HOST=localhost
ENV MSSQL_USER=your_username
ENV MSSQL_PASSWORD=your_password
ENV MSSQL_DATABASE=your_database

# Command to run the MCP server
ENTRYPOINT ["python", "-m", "mssql_mcp_server"]
